#
#    Makefile for Etoile PreferencesKitExample
#

ifeq ($(debug), yes)
	extension = debug
else
	extension = app
endif

before-all::

after-all::
	mkdir -p $(CURDIR)/PreferencesKitExample.$(extension)/PlugIns; \
	cp -Rfp $(CURDIR)/SamplePrefPane/SamplePrefPane.prefPane \
	$(CURDIR)/SamplePrefsModule/SamplePrefsModule.prefsModule \
	$(CURDIR)/PreferencesKitExample.$(extension)/PlugIns/; \

after-clean::

after-distclean::

