#
#    Makefile for Etoile PreferencesKitExample
#

export PROJECT_DIR ?= $(CURDIR)

ADDITIONAL_INCLUDE_DIRS += -I$(PROJECT_DIR)

ADDITIONAL_LIB_DIRS += -L$(PROJECT_DIR)/../../../Frameworks/PreferencesKit/Source/PreferencesKit.framework/Versions/Current


