#
#    Makefile for Etoile DistributedViewExample
#

before-all::
	rm -f $(CURDIR)/DistributedView
	$(LN_S) $(CURDIR)/../../../Frameworks/DistributedView $(CURDIR)/
	rm -f $(CURDIR)/EtoileUI
	$(LN_S) $(CURDIR)/../../../Frameworks/EtoileUI/Headers $(CURDIR)/EtoileUI

after-all::

after-clean::
	rm -f $(CURDIR)/DistributedView
	rm -f $(CURDIR)/EtoileUI

after-distclean::

