#
#    Makefile for Etoile DistributedViewExample
#

before-all::
	rm -f $(CURDIR)/EtoileExtensions
	$(LN_S) $(CURDIR)/../../../Frameworks/EtoileExtensionsKit/Headers $(CURDIR)/EtoileExtensions

after-all::

after-clean::
	rm -f $(CURDIR)/EtoileExtensions

after-distclean::

