include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = PaneKit_Source

PaneKit_Source_OBJC_FILES = \
        CocoaCompatibility.m \
        NSPreferencePane.m \
	PKPanesController.m \
        PKPreferencesController.m \
        PKPreferencePane.m \
        PKPresentationBuilder.m \
        PKTableViewPresentation.m \
        PKMatrixViewPresentation.m \
        PKMatrixView.m \
        PKToolbarPresentation.m \
        PKPlainPresentation.m \
        PKPrefPanesRegistry.m \
        PKPaneRegistry.m 

PaneKit_Source_INCLUDE_DIRS += -I..

ADDITIONAL_CFLAGS +=
ADDITIONAL_INCLUDE_DIRS += 
ADDITIONAL_LIB_DIRS += 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble

