include $(GNUSTEP_MAKEFILES)/common.make

OBJCFLAGS += -g -std=c99
LIBRARY_NAME = TRXML

TRXML_OBJC_FILES = TRXMLNode.m\
                   TRXMLNullHandler.m\
                   TRXMLParser.m\
                   TRXMLString.m

TRXML_HEADER_FILES = TRXMLNode.h\
                     TRXMLParser.h\
                     TRXMLString.h\
                     TRXMLNullHandler.h\
                     TRXMLParserDelegate.h

include $(GNUSTEP_MAKEFILES)/library.make
