#Make a temporary directory in order to have library/bundle compiled

before-all:: 
	if [ ! -h "MultimediaKit" ]; then \
	  $(LN_S) Headers MultimediaKit; \
	fi;

after-clean::
	if [ -h "MultimediaKit" ]; then \
	  rm MultimediaKit; \
	fi;

