include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = VolumeControlMenulet
BUNDLE_EXTENSION = .menulet

VolumeControlMenulet_OBJC_FILES = \
	VolumeControlMenulet.m 

VolumeControlMenulet_GUI_LIBS += \
	-lSystemConfig

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include ../../etoile.make
-include GNUmakefile.postamble

