PACKAGE_NAME = ServicesBarKit	

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = Source #ServicesBarMenulet #StatusItemExample 

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make
-include ../../etoile.make

-include GNUmakefile.postamble
