include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
TOOL_NAME = Microblogger

#
# Resource files
#
Microblogger_LANGUAGES = English


Microblogger_OBJC_FILES = \
	Microblogger.m\
	main.m

ADDITIONAL_OBJCFLAGS = -std=c99 -g -Werror -DGNUSTEP
ADDITIONAL_LDFLAGS += -g


include $(GNUSTEP_MAKEFILES)/tool.make
