include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.1
TOOL_NAME = Microblogger

Microblogger_LANGUAGES = English


Microblogger_OBJC_FILES = \
	Microblogger.m\
	main.m

Microblogger_OBJCFLAGS = -std=c99

include $(GNUSTEP_MAKEFILES)/tool.make
-include ../../../etoile.make
