include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Typewriter

Typewriter_OBJC_FILES = \
	main.m \
	TWTextView.m \
	TWDocument.m

Typewriter_LANGUAGES = \
	English

Typewriter_LOCALIZED_RESOURCE_FILES = \
	MainMenu.gorm \
	Document.gorm

Typewriter_MAIN_MODEL_FILE = MainMenu.gorm

include $(GNUSTEP_MAKEFILES)/application.make
