
include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = OPMLKit
OPMLKit_OBJC_FILES = \
	OPMLParser.m \
	OPMLDocument.m \
	OPMLOutline.m \

OPMLKit_HEADER_FILES = \
	OPMLParser.h \
	OPMLDocument.h \
	OPMLOutline.h \

include $(GNUSTEP_MAKEFILES)/library.make

-include ../../../../etoile.make

