
include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME = OPMLKit
OPMLKit_OBJC_FILES = \
	OPMLParser.m \
	OPMLDocument.m \
	OPMLOutline.m \

OPMLKit_HEADER_FILES = \
	OPMLParser.h \
	OPMLDocument.h \
	OPMLOutline.h \

include $(GNUSTEP_MAKEFILES)/aggregate.make
-include ../../etoile.make
include $(GNUSTEP_MAKEFILES)/framework.make


