include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
TOOL_NAME = ColloquySetStatus

#
# Resource files
#
ColloquySetStatus_LANGUAGES = English


ColloquySetStatus_OBJC_FILES = \
	ColloquySetStatus.m\
	main.m

ADDITIONAL_OBJCFLAGS = -std=c99 -g -Werror
ADDITIONAL_LDFLAGS += -g


include $(GNUSTEP_MAKEFILES)/tool.make
