include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = MixerExample

MixerExample_PRINCIPAL_CLASS = NSApplication

MixerExample_GUI_LIBS += -lMultimediaKit

MixerExample_OBJC_FILES = \
	main.m

include $(GNUSTEP_MAKEFILES)/application.make

