#
# GNUmakefile - Workflow
#
# Copyright 2007 Isaiah Beerbower.
#
# Author: Isaiah Beerbower
# Created: 03/27/07
# License: Modified BSD license (see file COPYING)
#

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
  Framework \
  Application \
  Modules

include $(GNUSTEP_MAKEFILES)/aggregate.make

include ../../../etoile.make
