######################################
#    ETOILE DOCUMENTATION SCRIPTS    #
######################################

# the developper has to define the following:
# MARKDOWN_DOCUMENTATION_FILES = myclass-overview.text
# OBJC_DOCUMENTATION_FILES = myclass.h

######################################

# default values for the directory output, etc.

ifeq ($(ETOILE_DOCUMENTATION_DIRECTORY),)
	ETOILE_DOCUMENTATION_DIRECTORY = Documentation
endif

ifeq ($(ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY),)
	ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY = $(ETOILE_DOCUMENTATION_DIRECTORY)/generated
endif

ifeq ($(ETOILE_DOCUMENTATION_TEMPLATE),)
	ETOILE_DOCUMENTATION_TEMPLATE = $(ETOILE_DOCUMENTATION_DIRECTORY)/etoile-documentation-template.html
endif

ifeq ($(ETOILE_DOCUMENTATION_TEMPLATE_MARKDOWN),)
	ETOILE_DOCUMENTATION_TEMPLATE_MARKDOWN = $(ETOILE_DOCUMENTATION_DIRECTORY)/etoile-documentation-markdown-template.html
endif

ifeq ($(ETOILE_DOCUMENTATION_CLASS_MAPPING),)
	ETOILE_DOCUMENTATION_CLASS_MAPPING = $(ETOILE_DOCUMENTATION_DIRECTORY)/class-mapping.plist
endif

ifeq ($(ETOILE_DOCUMENTATION_PROJECT_CLASS_MAPPING),)
	ETOILE_DOCUMENTATION_PROJECT_CLASS_MAPPING = $(ETOILE_DOCUMENTATION_DIRECTORY)/project-class-mapping.plist
endif

ifeq ($(ETOILE_DOCUMENTATION_PROJECT_MENU),)
	ETOILE_DOCUMENTATION_PROJECT_MENU = $(ETOILE_DOCUMENTATION_DIRECTORY)/menu.html
endif

# Tools we use...

AUTOGSDOC_FLAGS = -DocumentationDirectory $(ETOILE_DOCUMENTATION_DIRECTORY) -GenerateHtml NO
MARKDOWN = markdown
GSDOC_GENERATOR = autogsdoc
ETOILE_DOC_GENERATOR = ETDocGenerator

# automatic rules to generate documentation

$(ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY)/%.html : $(ETOILE_DOCUMENTATION_DIRECTORY)/%.text
	$(MARKDOWN) -o $(ETOILE_DOCUMENTATION_DIRECTORY)/$*.html $<
	$(ETOILE_DOC_GENERATOR) -i $(ETOILE_DOCUMENTATION_DIRECTORY)/$*.html \
		-o $@ \
		-t $(ETOILE_DOCUMENTATION_TEMPLATE_MARKDOWN) \
		-m $(ETOILE_DOCUMENTATION_PROJECT_MENU) \
		-c $(ETOILE_DOCUMENTATION_CLASS_MAPPING) \
		-p $(ETOILE_DOCUMENTATION_PROJECT_CLASS_MAPPING)

%.gsdoc : %.h
	$(GSDOC_GENERATOR) $(AUTOGSDOC_FLAGS) $<
	$(ETOILE_DOC_GENERATOR) -i $(ETOILE_DOCUMENTATION_DIRECTORY)/$@ \
	 	-o $(ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY)/$*.html \
		-t $(ETOILE_DOCUMENTATION_TEMPLATE) \
		-m $(ETOILE_DOCUMENTATION_PROJECT_MENU) \
		-c $(ETOILE_DOCUMENTATION_CLASS_MAPPING) \
		-p $(ETOILE_DOCUMENTATION_PROJECT_CLASS_MAPPING)

%.gsdoc : %.m
	$(GSDOC_GENERATOR) $(AUTOGSDOC_FLAGS) $<
	$(ETOILE_DOC_GENERATOR) -i $(ETOILE_DOCUMENTATION_DIRECTORY)/$@ \
	 	-o $(ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY)/$*.html \
		-t $(ETOILE_DOCUMENTATION_TEMPLATE) \
		-m $(ETOILE_DOCUMENTATION_PROJECT_MENU) \
		-c $(ETOILE_DOCUMENTATION_CLASS_MAPPING) \
		-p $(ETOILE_DOCUMENTATION_PROJECT_CLASS_MAPPING)

generate-gsdoc: $(patsubst %.m,%.gsdoc, $(patsubst %.h,%.gsdoc, $(OBJC_DOCUMENTATION_FILES)))

generate-markdown: $(patsubst %.text,%.html, $(patsubst %,$(ETOILE_DOCUMENTATION_OUTPUT_DIRECTORY)/%,$(MARKDOWN_DOCUMENTATION_FILES)))

# etoile documentation depends on markdown documents (if they are defined) and gsdoc documents

etoile-doc: generate-markdown generate-gsdoc
