#
# GNUmakefile - Workflow
#
# Copyright 2007 Isaiah Beerbower.
#
# Author: Isaiah Beerbower
# Created: 03/27/07
# License: Modified BSD license (see file COPYING)
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Workflow

Workflow_OBJC_FILES = \
  WFMain.m \
  WFDocument.m \
  WFObject.m \
  WFObjectDrawing.m \
  WFView.m

Workflow_LANGUAGES = \
  English

Workflow_LOCALIZED_RESOURCE_FILES = \
  MainMenu.gorm \
  Document.gorm

Workflow_MAIN_MODEL_FILE = MainMenu.gorm

include $(GNUSTEP_MAKEFILES)/application.make
