include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Extensions

Extensions_OBJC_FILES = \
	BezierPathExtensions.m \
	CalendarExtensions.m \
	ClickableProgressIndicator.m \
	PopUpButtonExtensions.m \
	SplitViewExtensions.m \
	TableViewExtensions.m \
	ViewExtensions.m

include $(GNUSTEP_MAKEFILES)/subproject.make

