include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME=WorkspaceCommKit

$(LIBRARY_NAME)_OBJC_FILES=$(wildcard *.m)
$(LIBRARY_NAME)_HEADER_FILES=$(wildcard *.h)

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
include ../../../../etoile.make
-include GNUmakefile.postamble
