PACKAGE_NAME = Aristo2

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Aristo2
BUNDLE_EXTENSION = .theme

$(BUNDLE_NAME)_INSTALL_DIR = $(GNUSTEP_LIBRARY)/Themes

$(BUNDLE_NAME)_OBJC_FILES = 

$(BUNDLE_NAME)_RESOURCE_FILES = \
	Resources/Info-gnustep.plist \
	Resources/ThemeImages \
	Resources/ThemeTiles \
	Resources/*.clr

include $(GNUSTEP_MAKEFILES)/bundle.make
-include ../../etoile.make
