
PaneKit_HEADER_FILES_DIR = ./PaneKit
PaneKit_HEADER_FILES_INSTALL_DIR = PaneKit
PaneKit_HEADER_FILES = \
	CocoaCompatibility.h \
	NSPreferencePane.h \
	PKPreferencesController.h \
	PKPreferencePane.h \
	PKPresentationBuilder.h \
	PKTableViewPresentation.h \
	PKMatrixViewPresentation.h \
	PKPlainPresentation.h \
	PKPrefPanesRegistry.h \
	UKPluginsRegistry.h \
	PaneKit.h

