include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = PowerMenulet
BUNDLE_EXTENSION = .menulet

PowerMenulet_OBJC_FILES = \
	PowerMenulet.m 

PowerMenulet_RESOURCE_FILES = \
	Resources/*.tiff

PowerMenulet_GUI_LIBS += \
	-lSystemConfig

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

