#Make a temporary directory in order to have library/bundle compiled

before-all:: 
	if [ ! -h "BookmarkKit" ]; then \
	  $(LN_S) Headers BookmarkKit; \
	fi;

after-clean::
	if [ -h "BookmarkKit" ]; then \
	  rm BookmarkKit; \
	fi;

