BookmarkKit_HEADER_FILES_DIR = ./BookmarkKit
BookmarkKit_HEADER_FILES_INSTALL_DIR = /BookmarkKit
BookmarkKit_HEADER_FILES = \
    BookmarkKit.h \
    BKBookmark.h \
    BKBookmarkQuery.h \
    BKBookmarkSearchResult.h \
    BKBookmarkStore.h

