include $(GNUSTEP_MAKEFILES)/common.make

#TOOL_NAME = URLTest
APP_NAME = URLTest

URLTest_OBJC_FILES = \
	main.m

#include $(GNUSTEP_MAKEFILES)/tool.make
include $(GNUSTEP_MAKEFILES)/application.make


