#
#    Makefile for Etoile LuceneKitExample
#

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = LuceneKitExample

LuceneKitExample_OBJC_FILES = \
	LuceneKitExample.m 

LuceneKitExample_TOOL_LIBS = -lLuceneKit -lOgreKit -lgnustep-gui

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
