include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = LuceneKitExample

LuceneKitExample_OBJC_FILES = \
	LuceneKitExample.m 

LuceneKitExample_INCLUDE_DIRS += 
LuceneKitExample_LDFLAGS += -lLuceneKit 

include $(GNUSTEP_MAKEFILES)/tool.make

-include ../GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include ../GNUmakefile.postamble
