include $(GNUSTEP_MAKEFILES)/common.make

GNUSTEP_MAKEINFO_FLAGS = -D NO-TEXI2HTML

DOCUMENT_NAME = DeveloperGuide

DeveloperGuide_TEXI_FILES = \
	DeveloperGuide.texi \
	ObjectMerging.texi


include $(GNUSTEP_MAKEFILES)/documentation.make
