include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.1
APP_NAME = StatusExample

StatusExample_LANGUAGES = English

StatusExample_LOCALIZED_RESOURCE_FILES = \
	  MainMenu.gorm

StatusExample_MAIN_MODEL_FILE = MainMenu.gorm

StatusExample_OBJC_FILES = \
	StatusExample.m\
	main.m

StatusExample_OBJCFLAGS = -std=c99

include $(GNUSTEP_MAKEFILES)/application.make
-include ../../../etoile.make
