include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = TrashCan

TrashCan_OBJC_FILES = \
	TrashInfo.m \
	TrashCanView.m \
	TrashCan.m \
	main.m 

ADDITIONAL_INCLUDE_DIRS += 

ADDITIONAL_LIB_DIRS += \
	-lXWindowServerKit 

ADDITIONAL_GUI_LIBS += 

include $(GNUSTEP_MAKEFILES)/application.make
include $(GNUSTEP_MAKEFILES)/aggregate.make
include ../../../etoile.make

