include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Source

Source_SUBPROJECTS = \
	RegularExpression \
	FindPanel

include $(GNUSTEP_MAKEFILES)/subproject.make
include $(GNUSTEP_MAKEFILES)/aggregate.make

