before-all::
	rm -f $(CURDIR)/PKPrefsModulePrefPane.m
	$(LN_S) $(CURDIR)/BackboneCompatibility/PKPrefsModulePrefPane.m \
		$(CURDIR)/PKPrefsModulePrefPane.m
	rm -f $(CURDIR)/../Headers/PrefsModule.h
	$(LN_S) $(CURDIR)/../Headers/BackboneCompatibility/PrefsModule.h \
		$(CURDIR)/../Headers/PrefsModule.h

after-all::
	rm -f $(CURDIR)/PKPrefsModulePrefPane.m

after-clean::
	rm -f $(CURDIR)/PKPrefsModulePrefPane.m
	rm -f $(CURDIR)/../Headers/PrefsModule.h

after-distclean::

