include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = WildMenus
BUNDLE_EXTENSION=.themeEngine

ADDITIONAL_OBJCFLAGS = -g -Wall -O2 
#ADDITIONAL_OBJCFLAGS = -O2 

WildMenus_OBJC_FILES = WildMenus.m \
GSHorizontalMenuItemCell.m \
NSMenuView+Hackery.m \
GSHorizontalMenuView.m \
NSApplication+Hackery.m \
MHMenuItemCell.m \
NSMenu+Hackery.m

WildMenus_PRINCIPAL_CLASS = WildMenus

include $(GNUSTEP_MAKEFILES)/bundle.make
