include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = ScriptServices

ScriptServices_OBJC_FILES = ScriptServices.m 

ScriptServices_RESOURCE_FILES = \
	Scripts

include $(GNUSTEP_MAKEFILES)/application.make

