PACKAGE_NAME = DummyKit

#
# Install location
#
GNUSTEP_SYSTEM_DOMAIN =

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = Source

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make
-include /path_to_repository_root/etoile.make

-include GNUmakefile.postamble
