GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Login

Login_OBJC_FILES = main.m NSFileHandle+line.m GDMClient.m Controller.m Background.m

Login_LANGUAGES = English

Login_RESOURCE_FILES = \
	login-images/Loader1.png \
	login-images/Loader2.png \
	login-images/Loader3.png \
	login-images/Loader4.png \
	login-images/Loader5.png \
	login-images/Loader6.png \
	login-images/Loader7.png \
	login-images/Loader8.png 

Login_LOCALIZED_RESOURCE_FILES = login.gorm

Login_MAIN_MODEL_FILE = login.gorm

include $(GNUSTEP_MAKEFILES)/application.make

