include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = libMultimediaKit

libMultimediaKit_OBJC_FILES = \
	MixerView.m \
	MixerChannelView.m \
	MixerChannel.m \
	Mixer.m \
	MPlayer.m \
	MPlayerInterface.m \
	MMPlayer.m 

-include ../GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/subproject.make

-include ../GNUmakefile.postamble

