include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = MultimediaKit
VERSION = 0.1

MultimediaKit_OBJC_FILES = \
	MixerView.m \
	MixerChannelView.m \
	MixerChannel.m \
	Mixer.m \
	MPlayer.m \
	MPlayerInterface.m \
	MMPlayer.m 

MultimediaKit_HEADER_FILES_DIR = ../Headers

MultimediaKit_HEADER_FILES_INSTALL_DIR = MultimediaKit

MultimediaKit_HEADER_FILES = \
	MixerView.h \
	MixerChannelView.h \
	MixerChannel.h \
	Mixer.h \
	MMPlayer.h \
	MPlayer.h \
	MPlayerInterface.h \
	MultimediaKit.h

-include ../GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
-include ../GNUmakefile.postamble
