# Install headers

CollectionKit_HEADER_FILES_DIR = ./CollectionKit
CollectionKit_HEADER_FILES_INSTALL_DIR = CollectionKit
CollectionKit_HEADER_FILES = \
	CollectionKit.h \
	CKSearchElement.h \
	CKCollection.h \
	CKGroup.h \
	CKItem.h \
	CKTypedefs.h \
	CKMultiValue.h \
	CKRecord.h \
	CKGlobals.h

