#Make a temporary directory in order to have library/bundle compiled

before-all:: 
	if [ ! -h "CollectionKit" ]; then \
	  $(LN_S) Headers CollectionKit; \
	fi;

after-clean::
	if [ -h "CollectionKit" ]; then \
	  rm CollectionKit; \
	fi;

