#
#    Makefile for Etoile PreferencesKitExample
#

before-all::
	
after-all::
ifeq ($(FOUNDATION_LIB), apple)
	cp -Rfp SamplePrefsModuleInfo_Cocoa.plist \
	SamplePrefsModule.prefsModule/Contents/Info.plist; 
endif

after-clean::

after-distclean::

