include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = SQLite3

SQLite3_OBJC_FILES = \
	SQLDatabase.m \
	SQLResult.m \
	SQLRow.m

SQLite3_C_FILES = \
	sqlite3.c

include $(GNUSTEP_MAKEFILES)/subproject.make

