ifeq ($(debug), yes)
	extension = debug
else
	extension = app
endif

before-all::

after-all::
	mkdir -p $(CURDIR)/LookAndBehavior.$(extension)/PlugIns; \
	cp -Rfp $(CURDIR)/AppearancePrefPane/AppearancePrefPane.prefPane \
	$(CURDIR)/LanguagesPrefPane/LanguagesPrefPane.prefPane \
	$(CURDIR)/LookAndBehavior.$(extension)/PlugIns/; \

after-clean::

after-distclean::

