#
# Makefile for LookAndBehavior
#

before-all::

after-all::
	mkdir -p $(CURDIR)/LookAndBehavior.app/PlugIns; \
	cp -Rfp $(CURDIR)/AppearancePrefPane/AppearancePrefPane.prefPane \
	$(CURDIR)/LanguagesPrefPane/LanguagesPrefPane.prefPane \
	$(CURDIR)/LookAndBehavior.app/PlugIns/; \

after-clean::

after-distclean::
