include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = LuceneKit_Search

LuceneKit_Search_OBJC_FILES = \
	LCSimilarity.m 

LuceneKit_Search_INCLUDE_DIRS += -I../../Headers -I../

include $(GNUSTEP_MAKEFILES)/subproject.make
