include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = LuceneKit_Search

LuceneKit_Search_OBJC_FILES = \
	LCTopDocs.m \
	LCTopFieldDocs.m \
	LCScoreDoc.m \
	LCFieldDoc.m \
	LCFilter.m \
	LCFieldCache.m \
	LCFieldCacheImpl.m \
	LCFieldSortedHitQueue.m \
	LCHitCollector.m \
	LCHitQueue.m \
	LCExplanation.m \
	LCQuery.m \
	LCIndexSearcher.m \
	LCSearcher.m \
	LCScorer.m \
	LCSortField.m \
	LCScoreDocComparator.m \
	LCSort.m \
	LCSortComparator.m \
	LCSimilarity.m  \
	LCDefaultSimilarity.m \
	LCSimilarityDelegator.m 

LuceneKit_Search_INCLUDE_DIRS += -I../../Headers -I../

-include ../../GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include ../../GNUmakefile.postamble
