include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = SQLiteClientExample
SQLiteClientExample_OBJC_FILES = SQLiteClientExample.m
SQLiteClientExample_TOOL_LIBS += -lSQLClient 
SQLiteClientExample_LIB_DIRS += -L./obj -L/opt/local/lib

include $(GNUSTEP_MAKEFILES)/tool.make

