include $(GNUSTEP_MAKEFILES)/common.make

#
# Main framework
#
LIBRARY_NAME = DummyKit
VERSION = 0.1

#
# Resource files
#
DummyKit_MAIN_MODEL_FILE =

DummyKit_RESOURCE_FILES =

DummyKit_LOCALIZED_RESOURCE_FILES =

#
# Languages we're localized for
#
DummyKit_LANGUAGES = \
	English

#
# Class files
#
DummyKit_OBJC_FILES = \
	PartOfDummy.m

#
# C files
#
DummyKit_C_FILES =

#
# Header files to install
#
DummyKit_HEADER_FILES_DIR = ../Headers

DummyKit_HEADER_FILES_INSTALL_DIR = DummyKit

DummyKit_HEADER_FILES = \
	DummyKit.h \
	PartOfDummy.h

-include ../GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/library.make

-include ../GNUmakefile.postamble
