include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = libInspectorKit

libInspectorKit_OBJC_FILES = \
	FilePopUpPresentation.m \
	ToolsPane.m \
	AttributesPane.m \
	OSDateView.m \
	Inspector.m \
	PermissionsView.m

libInspectorKit_LIBRARIES_DEPEND_UPON = -lIconKit -lPaneKit

include $(GNUSTEP_MAKEFILES)/subproject.make

