all:: ProjectManagerNotes.pdf

# Yes, we run three times to get each pass correct. 
ProjectManagerNotes.pdf: ProjectManagerNotes.tex
	pdflatex ProjectManagerNotes.tex
	pdflatex ProjectManagerNotes.tex
	pdflatex ProjectManagerNotes.tex
