include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = ServiceMenulet
BUNDLE_EXTENSION = .menulet

ServiceMenulet_OBJC_FILES = \
	ServiceMenulet.m 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

