include $(GNUSTEP_MAKEFILES)/common.make

ADDITIONAL_OBJCFLAGS = -Wno-import

ADDITIONAL_INCLUDE_DIRS = -I../Headers

GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)

#
# Main application
#
LIBRARY_NAME = libTrackerKit	
VERSION = 0.1

#
# Resource files
#
libTrackerKit_MAIN_MODEL_FILE =

libTrackerKit_RESOURCE_FILES =

libTrackerKit_LOCALIZED_RESOURCE_FILES =

#
# Languages we're localized for
#
libTrackerKit_LANGUAGES = \
	English
	
#
# Class files
#
libTrackerKit_OBJC_FILES = 

#
# C files
#
libTrackerKit_C_FILES =

#
# Header files
#
libTrackerKit_HEADER_FILES_DIR = ../Headers

libTrackerKit_HEADER_FILES_INSTALL_DIR = /TrackerKit

libTrackerKit_HEADER_FILES = 
	
-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/library.make

-include GNUmakefile.postamble
