#Make a temporary directory in order to have library/bundle compiled

before-all:: 
	if [ ! -h "PaneKit" ]; then \
	  $(LN_S) Headers PaneKit; \
	fi;

after-clean::
	if [ -h "PaneKit" ]; then \
	  rm PaneKit; \
	fi;

