
PaneKit_HEADER_FILES_DIR = ./PaneKit
PaneKit_HEADER_FILES_INSTALL_DIR = PaneKit
PaneKit_HEADER_FILES = \
	CocoaCompatibility.h \
	PKPresentationBuilder.h \
	PKPreferencesController.h \
	PKPreferencePaneRegistry.h \
	PKPreferencePane.h \
	NSPreferencePane.h \
	PKPanesController.h \
	PKPaneRegistry.h \
	PKPane.h \
	PaneKit.h

