#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = StepChat
APP_NAME = StepChat
StepChat_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DIR = $(HOME)/GNUstep


#
# Resource files
#
StepChat_RESOURCE_FILES = \
GNUstep/MainMenu.gorm\
GNUstep/Info-gnustep.plist

#
# Header files
#
StepChat_HEADER_FILES = \
AddContactWindowController.h \
ChatLog.h \
Conversation.h \
CustomPresenceWindowController.h \
DefaultHandler.h \
Dispatcher.h \
GroupChat.h \
HideMenuController.h \
JabberApp.h \
JabberIdentity.h \
JabberPerson.h \
JID.h \
Message.h \
MessageWindowController.h \
PasswordWindowController.h \
PreferenceWindowController.h \
Presence.h \
PresenceMenuController.h \
query_jabber_iq_auth.h \
Roster.h \
roster_item.h \
RosterController.h \
RosterGroup.h \
Timestamp.h \
TRUserDefaults.h \
TRXML/TRXMLNode.h \
TRXML/TRXMLParser.h \
TRXML/TRXMLParserDelegate.h \
XMPPAccount.h \
XMPPConnection.h

#
# Class files
#
StepChat_OBJC_FILES = \
AddContactWindowController.m \
ChatLog.m \
Conversation.m \
CustomPresenceWindowController.m \
DefaultHandler.m \
Dispatcher.m \
GroupChat.m \
HideMenuController.m \
JabberApp.m \
JabberIdentity.m \
JabberPerson.m \
JID.m \
Message.m \
MessageWindowController.m \
PreferenceWindowController.m \
Presence.m \
PresenceMenuController.m \
query_jabber_iq_auth.m \
Roster.m \
RosterController.m \
RosterGroup.m \
Timestamp.m \
TRUserDefaults.m \
TRXML/TRXMLNode.m \
TRXML/TRXMLParser.m \
XMPPAccount.m \
XMPPConnection.m

#PasswordWindowController.m \

#
# C files
#
StepChat_C_FILES = 

StepChat_OBJC_FILES += \
main.m 

ADDITIONAL_OBJCFLAGS = -DGNUSTEP -std=c99 -Wno-import -ITRXML

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
