include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = EtoileThreadTest
$(TOOL_NAME)_OBJC_FILES = \
	ETThreadTest.m
$(TOOL_NAME)_TOOL_LIBS += -lgnustep-base -lgnustep-gui -lEtoileFoundation

include $(GNUSTEP_MAKEFILES)/tool.make
-include ../../../etoile.make
