include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = LuceneKit_QueryParser

LuceneKit_QueryParser_OBJC_FILES = \
	LCQueryParser.m

LuceneKit_QueryParser_INCLUDE_DIRS += -I../..

-include ../../GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include ../../GNUmakefile.postamble
