include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = LuceneKit_Source

LuceneKit_Source_SUBPROJECTS = \
	Search \
	Index \
	Analysis \
	Document \
	Store \
	Util \
	Java

include $(GNUSTEP_MAKEFILES)/subproject.make

-include ../GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include ../GNUmakefile.postamble
