/* config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */
/* define to the path to cpp */
#define CPP_PATH "/usr/bin/cpp"

/* package name */
/* #undef PACKAGE */

/* package version */
#define VERSION "0.1"

/* define if you want GNOME stuff support */
/* #undef GNOME_STUFF */

/* define if you want KDE hint support */
/* #undef KWM_HINTS */

/* define if you want OPEN LOOK(tm) hint support */
/* #undef OLWM_HINTS */

/* define if XPM libraries are available
 * set by configure */
#define USE_XPM 1

/* define if PNG libraries are available
 * set by configure */
#define USE_PNG 1

/* define if JPEG libraries are available
 * set by configure */
#define USE_JPEG 1

/* define if GIF libraries are available
 * set by configure */
#define USE_GIF 1

/* define if TIFF libraries are available
 * set by configure */
#define USE_TIFF 1

/* define if X's shared memory extension is available
 * set by configure */
#define XSHM 1

/* define an extra path for pixmaps
 * set by configure */
#define PIXMAPDIR "/usr/local/share/pixmaps"

/* Internationalization (I18N) support
 * set by configure */
/* #undef I18N */

/* define if you want the 'lite' version */
/* #undef LITE */

/* define if you want support for shaped windows
 * set by configure */
#define SHAPE 1

/* define if you want support for the XINERAMA extension
 * set by configure */
/* #undef XINERAMA */

/* define if you want support for X window's X_LOCALE
 * set by configure */
/* #undef X_LOCALE */

/* the place where shared data is stored
 * defined by configure */
#define PKGDATADIR "/usr/local/share/WindowMaker"

/* the place where the configuration is stored
 * defined by configure */
#define SYSCONFDIR "/usr/local/etc"

/* whether XKB language MODELOCK should be enabled */
/* #undef XKB_MODELOCK */

/* define if you want user defined menus for applications */
/* #undef USER_MENU */

/* define if you have then inet_aton function */
#define HAVE_INET_ATON 1

/* define if your X server has XInternAtoms() */
#define HAVE_XINTERNATOMS 1

/* define if your X server has XConvertCase() */
#define HAVE_XCONVERTCASE 1

/* define if you want Hermes support */
/* #undef HAVE_HERMES */

/* define if you have vsnprintf with C99 semantics */
#define HAVE_C99_VSNPRINTF 1


/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have the `atexit' function. */
#define HAVE_ATEXIT 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the `mallinfo' function. */
#define HAVE_MALLINFO 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* Define to 1 if you have the <poll.h> header file. */
#define HAVE_POLL_H 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Name of package */
/* #undef PACKAGE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "BUG-REPORT-ADDRESS"

/* Define to the full name of this package. */
#define PACKAGE_NAME "FULL-PACKAGE-NAME"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FULL-PACKAGE-NAME VERSION"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "full-package-name"

/* Define to the version of this package. */
#define PACKAGE_VERSION "VERSION"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
        STACK_DIRECTION > 0 => grows toward higher addresses
        STACK_DIRECTION < 0 => grows toward lower addresses
        STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if `sys_siglist' is declared by <signal.h> or <unistd.h>. */
/* #undef SYS_SIGLIST_DECLARED */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "0.1"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
