include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = SmalltalkWorkspace

$(APP_NAME)_OBJC_FILES = $(wildcard *.m)

$(APP_NAME)_LANGUAGES = English

$(APP_NAME)_MAIN_MODEL_FILE = MainMenu.gorm
$(APP_NAME)_LOCALIZED_RESOURCE_FILES = MainMenu.gorm STWorkspace.gorm
$(APP_NAME)_GUI_LIBS = -lEtoileFoundation -lLanguageKit -lSmalltalkSupport

include $(GNUSTEP_MAKEFILES)/application.make

