#
#  GNUstep Makefile for the charset decoder/converter
#
#  Copyright (C) 2001-2004
#
#  Author: Ludovic Marcotte <ludovic@Sophos.ca>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#   
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. */

include $(GNUSTEP_MAKEFILES)/common.make

# The application to be compiled
APP_NAME = CharsetDecoder

# The Objective-C source files to be compiled
CharsetDecoder_OBJC_FILES = CharsetDecoder.m

# The Objective-C headers
CharsetDecoder_HEADERS = CharsetDecoder.h


include $(GNUSTEP_MAKEFILES)/application.make
