#
# GNUmakefile - Workflow
#
# Copyright 2007 Isaiah Beerbower.
#
# Author: Isaiah Beerbower
# Created: 04/03/07
# License: Modified BSD license (see file COPYING)
#

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
  Core

include $(GNUSTEP_MAKEFILES)/aggregate.make
